# Generated by Django 3.0.7 on 2021-07-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allform', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
